sudo: required

language: python
python:
  - "2.7"
  - "3.6"

services: 
  - docker

before_install:
  - docker build -t volr/docker-nest-master -f ci/nest/src/master/Dockerfile ci/nest/src/master/
  - docker build -t volr/docker-nest-2.16.0 -f ci/nest/src/nest-2.16.0/Dockerfile ci/nest/src/nest-2.16.0/
  - docker build -t volr/nest-2.16.0 -f ci/Dockerfile-nest-2.16.0 .
  - docker run volr/volrpynn-nest-2.16.0 pytest /volrpynn/test-nest

install: pip install tox-travis

script: tox
